spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: 'jdbc:mysql://xempre.com:3306/gamingworld_evo'
        username: evo
        password: XempreDB
        driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
    swagger-ui:
        disable-swagger-default-url: true
server:
    port: 8081